language: php

php:
  - 5.6
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE zookeeper'

before_script:
  - phpenv config-add zookeeper.ini
  - cp config/config.example.php config/config.php
  - mysql -u root zookeeper < db/zkdbSchema.sql
  - mysql -u root zookeeper < db/categories.sql
  - mysql -u root zookeeper < db/chartemail.sql
  - mysql -u root zookeeper < db/bootstrapUser.sql

script: php zk test